-- Phase 08: shifts, physical cash movements, immutable Z close snapshots.
CREATE TYPE "ShiftStatus" AS ENUM ('OPEN','CLOSING','CLOSED');
CREATE TYPE "CashMovementType" AS ENUM ('CASH_IN','CASH_OUT','SAFE_DROP','ADJUSTMENT');
CREATE TABLE "Terminal" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL,"active" BOOLEAN NOT NULL DEFAULT TRUE,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Shift" ("id" TEXT PRIMARY KEY,"shiftNumber" BIGINT NOT NULL UNIQUE,"userId" TEXT NOT NULL REFERENCES "User"("id") ON DELETE RESTRICT,"terminalId" TEXT REFERENCES "Terminal"("id") ON DELETE RESTRICT,"status" "ShiftStatus" NOT NULL DEFAULT 'OPEN',"openedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"closedAt" TIMESTAMP(3),"openingCash" BIGINT NOT NULL,"countedCash" BIGINT,"expectedCashSnapshot" BIGINT,"difference" BIGINT,"closedByUserId" TEXT,"approvedByUserId" TEXT,"closeNote" TEXT,CONSTRAINT "Shift_openingCash_nonnegative" CHECK ("openingCash" >= 0),CONSTRAINT "Shift_countedCash_nonnegative" CHECK ("countedCash" IS NULL OR "countedCash" >= 0));
CREATE UNIQUE INDEX "one_open_shift_per_terminal" ON "Shift"("terminalId") WHERE "status"='OPEN' AND "terminalId" IS NOT NULL;
CREATE INDEX "Shift_status_openedAt_idx" ON "Shift"("status","openedAt");
CREATE TABLE "CashMovement" ("id" TEXT PRIMARY KEY,"shiftId" TEXT NOT NULL REFERENCES "Shift"("id") ON DELETE RESTRICT,"type" "CashMovementType" NOT NULL,"amount" BIGINT NOT NULL,"reason" TEXT NOT NULL,"performedByUserId" TEXT NOT NULL,"approvedByUserId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "CashMovement_amount_positive" CHECK ("amount">0));
CREATE INDEX "CashMovement_shift_created_idx" ON "CashMovement"("shiftId","createdAt");
CREATE TABLE "ZReportSnapshot" ("id" TEXT PRIMARY KEY,"reportNumber" TEXT NOT NULL UNIQUE,"shiftId" TEXT NOT NULL UNIQUE REFERENCES "Shift"("id") ON DELETE RESTRICT,"generatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"generatedByUserId" TEXT NOT NULL,"openingCash" BIGINT NOT NULL,"cashPayments" BIGINT NOT NULL,"cashRefunds" BIGINT NOT NULL,"cashReversals" BIGINT NOT NULL,"cashIn" BIGINT NOT NULL,"cashOut" BIGINT NOT NULL,"safeDrops" BIGINT NOT NULL,"adjustments" BIGINT NOT NULL,"expectedCash" BIGINT NOT NULL,"countedCash" BIGINT NOT NULL,"difference" BIGINT NOT NULL,"grossSales" BIGINT NOT NULL,"discounts" BIGINT NOT NULL,"netSales" BIGINT NOT NULL,"taxTotal" BIGINT NOT NULL,"refundsTotal" BIGINT NOT NULL,"orderCount" INTEGER NOT NULL,"idempotencyKey" TEXT NOT NULL UNIQUE,"snapshotVersion" INTEGER NOT NULL DEFAULT 1);
