import { createHash, randomBytes, scryptSync, timingSafeEqual } from "node:crypto";
import { cookies } from "next/headers";
import { db } from "./db";
export const SESSION_COOKIE="swifttill_session";
export function verifyPin(pin:string, encoded:string){const p=encoded.split("$");if(p.length!==3||p[0]!=="scrypt")return false;try{const salt=Buffer.from(p[1],"hex"), expected=Buffer.from(p[2],"hex"), actual=scryptSync(pin,salt,expected.length);return expected.length===actual.length&&timingSafeEqual(expected,actual)}catch{return false}}
export function hashPin(pin:string){if(!/^\d{4,12}$/.test(pin))throw new Error("PIN_FORMAT");const salt=randomBytes(16);return `scrypt$${salt.toString("hex")}$${scryptSync(pin,salt,32).toString("hex")}`}
const tokenHash=(token:string)=>createHash("sha256").update(token).digest("hex");
export async function createSession(userId:string,terminalId?:string){const token=randomBytes(32).toString("base64url");await db.session.create({data:{userId,tokenHash:tokenHash(token),terminalId,expiresAt:new Date(Date.now()+12*60*60*1000)}});return token}
export async function getSession(){const token=(await cookies()).get(SESSION_COOKIE)?.value;if(!token)return null;return db.session.findFirst({where:{tokenHash:tokenHash(token),revokedAt:null,expiresAt:{gt:new Date()},user:{active:true}},include:{user:{include:{roles:{include:{role:{include:{permissions:{include:{permission:true}}}}}},permissionOverrides:{include:{permission:true}}}}}})}
export async function effectivePermissions(){const session=await getSession();if(!session)return {session:null,permissions:new Set<string>()};const roleGrants=new Set(session.user.roles.filter(x=>x.role.active).flatMap(x=>x.role.permissions.map(r=>r.permission.key)));for(const o of session.user.permissionOverrides)if(o.effect==="ALLOW")roleGrants.add(o.permission.key);for(const o of session.user.permissionOverrides)if(o.effect==="DENY")roleGrants.delete(o.permission.key);return {session,permissions:roleGrants}}
export async function requirePermission(key:string){const r=await effectivePermissions();if(!r.session)throw Object.assign(new Error("UNAUTHENTICATED"),{status:401});if(!r.permissions.has(key))throw Object.assign(new Error("PERMISSION_DENIED"),{status:403});return r.session}
export async function revokeCurrentSession(){const token=(await cookies()).get(SESSION_COOKIE)?.value;if(token)await db.session.updateMany({where:{tokenHash:tokenHash(token),revokedAt:null},data:{revokedAt:new Date()}})}
