export type AuthContext = Readonly<{userId:string; companyId:string; sessionId:string; permissions:readonly string[]}>;
export function requireAuth(ctx:AuthContext|undefined):AuthContext { if(!ctx?.userId||!ctx.companyId||!ctx.sessionId) throw new Error("UNAUTHENTICATED"); return ctx; }
export function requirePermission(ctx:AuthContext|undefined, permission:string):AuthContext { const a=requireAuth(ctx); if(!a.permissions.includes(permission)) throw new Error("FORBIDDEN"); return a; }
export function assertTenantOwnership(ctx:AuthContext, entity:{companyId:string}|null|undefined):void { if(!entity || entity.companyId!==ctx.companyId) throw new Error("NOT_FOUND"); }
export function assertOwnedChild(parentId:string, child:{parentId:string}|null|undefined):void { if(!child || child.parentId!==parentId) throw new Error("NOT_FOUND"); }
export function assertMoneyMinorUnits(value:number):void { if(!Number.isSafeInteger(value)||value<0) throw new Error("INVALID_MONEY_MINOR_UNITS"); }
export function assertExpectedVersion(current:number, expected:number):void { if(!Number.isInteger(expected)||expected<1) throw new Error("INVALID_VERSION"); if(current!==expected) throw new Error("VERSION_CONFLICT"); }
export function normalizePage(input:{limit?:number;cursor?:string}):Readonly<{limit:number;cursor?:string}>{ const limit=input.limit??50; if(!Number.isInteger(limit)||limit<1||limit>100) throw new Error("INVALID_PAGE_LIMIT"); return {limit,cursor:input.cursor?.trim()||undefined}; }
export function assertIdempotencyKey(key:string|undefined):string { const v=key?.trim(); if(!v||v.length<8||v.length>128) throw new Error("INVALID_IDEMPOTENCY_KEY"); return v; }
export function assertReason(reason:string|undefined,min=3,max=500):string { const v=reason?.trim()??""; if(v.length<min||v.length>max) throw new Error("INVALID_REASON"); return v; }
export function reconciliationDifference(input:{netSales:number;netLedger:number}):number { assertMoneyMinorUnits(input.netSales); assertMoneyMinorUnits(input.netLedger); return input.netLedger-input.netSales; }
export function assertReconciled(input:{netSales:number;netLedger:number;tolerance?:number}):void { const tolerance=input.tolerance??0; assertMoneyMinorUnits(tolerance); if(Math.abs(reconciliationDifference(input))>tolerance) throw new Error("RECONCILIATION_MISMATCH"); }
export function immutableSnapshot<T extends object>(value:T):Readonly<T>{ return Object.freeze(structuredClone(value)); }
export function shouldRetrySerializable(errorCode:string,attempt:number,maxAttempts=3):boolean { return ["P2034","40001","40P01"].includes(errorCode)&&attempt<maxAttempts; }
export async function withSerializableRetry<T>(work:(attempt:number)=>Promise<T>,codeOf:(e:unknown)=>string,maxAttempts=3):Promise<T>{ if(maxAttempts<1||maxAttempts>5) throw new Error("INVALID_RETRY_LIMIT"); for(let attempt=1;;attempt++){ try{return await work(attempt);}catch(e){if(!shouldRetrySerializable(codeOf(e),attempt,maxAttempts))throw e;} } }
export function redactAuditMetadata(value:unknown):unknown { const secret=/pin|password|token|secret|authorization|cookie/i; if(Array.isArray(value)) return value.map(redactAuditMetadata); if(value&&typeof value==="object"){return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([k,v])=>[k,secret.test(k)?"[REDACTED]":redactAuditMetadata(v)]));} return value; }
export function assertRequestActor(ctx:AuthContext,actorUserId:string):void { if(ctx.userId!==actorUserId) throw new Error("ACTOR_SPOOFING_REJECTED"); }
export function safePublicError(error:unknown):Readonly<{code:string;message:string}>{ const code=error instanceof Error&&/^[A-Z0-9_]+$/.test(error.message)?error.message:"INTERNAL_ERROR"; const publicCodes=new Set(["UNAUTHENTICATED","FORBIDDEN","NOT_FOUND","VERSION_CONFLICT","INVALID_VERSION","INVALID_PAGE_LIMIT","INVALID_IDEMPOTENCY_KEY","INVALID_REASON","RECONCILIATION_MISMATCH","ACTOR_SPOOFING_REJECTED","INVALID_MONEY_MINOR_UNITS"]); return publicCodes.has(code)?{code,message:code}:{code:"INTERNAL_ERROR",message:"INTERNAL_ERROR"}; }
