export type TenderName = "CASH" | "CARD" | "ONLINE";
export type OrderType = "DINE_IN" | "TAKEAWAY" | "DELIVERY";
export type ReportRange = { from:string; to:string; timezone:string };
export interface ReportLine { category:string; item:string; quantity:number; gross:bigint; discount:bigint; tax:bigint; total:bigint }
export interface ReportPayment { tender:TenderName; type:"PAYMENT"|"REVERSAL"|"REFUND"; amount:bigint; actorUserId:string }
export interface ReportOrder { id:string; orderNumber:bigint; businessDate:string; type:OrderType; operationalStatus:"OPEN"|"CLOSED"|"VOIDED"; financialStatus:string; cashierUserId:string; grossSubtotal:bigint; discountTotal:bigint; taxTotal:bigint; total:bigint; lines:ReportLine[]; payments:ReportPayment[] }
export interface SalesSummary { grossSales:bigint; discounts:bigint; netBeforeTax:bigint; tax:bigint; netSales:bigint; orderCount:number; averageOrder:bigint }
export interface NamedTotal { name:string; quantity:number; gross:bigint; discount:bigint; tax:bigint; total:bigint }
export interface TenderTotal { tender:TenderName; payments:bigint; reversals:bigint; refunds:bigint; net:bigint }
export interface CashierTotal { userId:string; orderCount:number; sales:bigint; payments:bigint }

export function assertRange(r:ReportRange){if(!r.from||!r.to||!r.timezone)throw new Error("REPORT_RANGE_REQUIRED");if(r.from>r.to)throw new Error("REPORT_RANGE_INVALID")}
export function eligibleOrders(orders:ReportOrder[]):ReportOrder[]{return orders.filter(o=>o.operationalStatus==="CLOSED" && o.financialStatus!=="UNPAID")}
export function salesSummary(orders:ReportOrder[]):SalesSummary{const xs=eligibleOrders(orders);const grossSales=xs.reduce((n,o)=>n+o.grossSubtotal,0n);const discounts=xs.reduce((n,o)=>n+o.discountTotal,0n);const tax=xs.reduce((n,o)=>n+o.taxTotal,0n);const netSales=xs.reduce((n,o)=>n+o.total,0n);return{grossSales,discounts,netBeforeTax:grossSales-discounts,tax,netSales,orderCount:xs.length,averageOrder:xs.length?netSales/BigInt(xs.length):0n}}
function groupLines(orders:ReportOrder[],key:(l:ReportLine)=>string):NamedTotal[]{const m=new Map<string,NamedTotal>();for(const o of eligibleOrders(orders))for(const l of o.lines){const k=key(l)||"Uncategorized";const x=m.get(k)??{name:k,quantity:0,gross:0n,discount:0n,tax:0n,total:0n};x.quantity+=l.quantity;x.gross+=l.gross;x.discount+=l.discount;x.tax+=l.tax;x.total+=l.total;m.set(k,x)}return [...m.values()].sort((a,b)=>a.name.localeCompare(b.name))}
export const categoryReport=(orders:ReportOrder[])=>groupLines(orders,l=>l.category);
export const itemReport=(orders:ReportOrder[])=>groupLines(orders,l=>l.item);
export function tenderReport(orders:ReportOrder[]):TenderTotal[]{const names:TenderName[]=["CASH","CARD","ONLINE"];return names.map(t=>{let payments=0n,reversals=0n,refunds=0n;for(const o of orders)for(const p of o.payments)if(p.tender===t){if(p.type==="PAYMENT")payments+=p.amount;else if(p.type==="REVERSAL")reversals+=p.amount;else refunds+=p.amount}return{tender:t,payments,reversals,refunds,net:payments-reversals-refunds}})}
export function cashierReport(orders:ReportOrder[]):CashierTotal[]{const m=new Map<string,CashierTotal>();for(const o of eligibleOrders(orders)){const x=m.get(o.cashierUserId)??{userId:o.cashierUserId,orderCount:0,sales:0n,payments:0n};x.orderCount++;x.sales+=o.total;for(const p of o.payments)if(p.actorUserId===o.cashierUserId)x.payments+=p.type==="PAYMENT"?p.amount:-p.amount;m.set(o.cashierUserId,x)}return [...m.values()].sort((a,b)=>a.userId.localeCompare(b.userId))}
export function reconcile(summary:SalesSummary,tenders:TenderTotal[]):{sales:bigint;tenderNet:bigint;difference:bigint}{const tenderNet=tenders.reduce((n,t)=>n+t.net,0n);return{sales:summary.netSales,tenderNet,difference:tenderNet-summary.netSales}}
const esc=(s:string)=>s.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
export function spreadsheetXml(title:string,headers:string[],rows:(string|number|bigint)[][]):string{const row=(v:(string|number|bigint)[])=>`<Row>${v.map(x=>`<Cell><Data ss:Type="${typeof x==="string"?"String":"Number"}">${esc(String(x))}</Data></Cell>`).join("")}</Row>`;return `<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="${esc(title.slice(0,31))}"><Table>${row(headers)}${rows.map(row).join("")}</Table></Worksheet></Workbook>`}
export interface PrintableReport { title:string; range:ReportRange; generatedAt:string; currencyCode:string; headers:string[]; rows:string[][]; totals:string[] }
export function printableReportHtml(r:PrintableReport):string{return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(r.title)}</title><style>body{font-family:Arial,sans-serif;margin:24px;color:#111}table{border-collapse:collapse;width:100%}th,td{border-bottom:1px solid #ddd;padding:8px;text-align:left}.meta{color:#555}.totals{font-weight:700;margin-top:16px}</style></head><body><h1>${esc(r.title)}</h1><p class="meta">${esc(r.range.from)} — ${esc(r.range.to)} · ${esc(r.range.timezone)}</p><table><thead><tr>${r.headers.map(h=>`<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>${r.rows.map(x=>`<tr>${x.map(v=>`<td>${esc(v)}</td>`).join("")}</tr>`).join("")}</tbody></table><p class="totals">${r.totals.map(esc).join(" · ")}</p></body></html>`}
export function thermalReport(title:string,lines:{label:string;value:string}[],width=42):string{if(width<30||width>48)throw new Error("THERMAL_WIDTH_INVALID");const center=(s:string)=>" ".repeat(Math.max(0,Math.floor((width-s.length)/2)))+s.slice(0,width);const lr=(a:string,b:string)=>a.slice(0,Math.max(1,width-b.length-1))+" ".repeat(Math.max(1,width-Math.min(a.length,width-b.length-1)-b.length))+b;return [center(title),"-".repeat(width),...lines.map(x=>lr(x.label,x.value)),"-".repeat(width)].join("\n")}
