import assert from "node:assert/strict"; import test from "node:test"; import { correctPaymentTender, refundOrder, refundOrderItems, voidOpenOrder, voidOrderItem, type CorrectionRepository } from "../src/correction-service.ts";
function repo():CorrectionRepository & {ledger:any[];idem:Map<string,any>;audits:any[]} { const r:any={ledger:[{id:"p1",orderId:"o1",type:"PAYMENT",tender:"CASH",amount:10000}],idem:new Map(),audits:[],transaction:async(fn:any)=>fn(r),lockOrder:async()=>({id:"o1",operationalStatus:"OPEN",financialStatus:"PAID",total:10000}),listLedger:async()=>r.ledger,findPayment:async(id:string)=>r.ledger.find((x:any)=>x.id===id)??null,findIdempotency:async(k:string)=>r.idem.get(k)??null,createLedger:async(d:any)=>{const x={id:`l${r.ledger.length+1}`,...d};r.ledger.push(x);return{id:x.id}},createRefund:async(d:any)=>({id:"r1",...d}),createOrderVoid:async()=>({id:"v1"}),setOrderOperationalStatus:async()=>{},releaseActiveTables:async()=>{},recalculateOpenOrderTotals:async()=>{},setOrderFinancialStatus:async()=>{},createIdempotency:async(d:any)=>r.idem.set(d.key,{fingerprint:d.fingerprint,result:d.result}),audit:async(d:any)=>r.audits.push(d),findOrderItem:async(id:string)=>id==="i1"?{id:"i1",orderId:"o1",quantity:2,lineGross:10000,lineDiscount:1000,lineTax:1350,lineTotal:10350}:id==="foreign"?{id:"foreign",orderId:"o2",quantity:1,lineGross:100,lineDiscount:0,lineTax:0,lineTotal:100}:null,listVoidedQuantity:async()=>0,createItemVoid:async(d:any)=>({id:"iv1",...d}),listRefundedQuantity:async()=>0,createRefundAllocation:async()=>{}}; return r; }
test("refund creates immutable refund ledger and is idempotent",async()=>{const r=repo();const i={orderId:"o1",amount:4000,tender:"CASH" as const,actorUserId:"u1",reason:"Customer return",idempotencyKey:"refund-1"};const a=await refundOrder(r,i);const b=await refundOrder(r,i);assert.deepEqual(a,b);assert.equal(r.ledger.filter(x=>x.type==="REFUND").length,1);assert.equal(a.financialStatus,"PARTIALLY_REFUNDED");});
test("second refund cannot exceed remaining amount",async()=>{const r=repo();await refundOrder(r,{orderId:"o1",amount:7000,tender:"CASH",actorUserId:"u1",reason:"Return",idempotencyKey:"r1"});await assert.rejects(()=>refundOrder(r,{orderId:"o1",amount:4000,tender:"CASH",actorUserId:"u1",reason:"Return",idempotencyKey:"r2"}),/remaining refundable/);});
test("payment tender correction preserves original and adds reversal plus replacement",async()=>{const r=repo();const out=await correctPaymentTender(r,{orderId:"o1",paymentId:"p1",newTender:"CARD",actorUserId:"u1",approvedByUserId:"m1",reason:"Wrong tender",idempotencyKey:"corr-1"});assert.equal(r.ledger[0].tender,"CASH");assert.deepEqual(r.ledger.map(x=>x.type),["PAYMENT","REVERSAL","PAYMENT"]);assert.equal(out.toTender,"CARD");assert.equal(r.audits.at(-1).action,"PAYMENT_CORRECTED");});
test("payment correction request is idempotent",async()=>{const r=repo();const i={orderId:"o1",paymentId:"p1",newTender:"CARD" as const,actorUserId:"u1",reason:"Wrong tender",idempotencyKey:"corr-1"};const a=await correctPaymentTender(r,i);const b=await correctPaymentTender(r,i);assert.deepEqual(a,b);assert.equal(r.ledger.length,3);});
test("paid order void is refused by service",async()=>{const r=repo();await assert.rejects(()=>voidOpenOrder(r,{orderId:"o1",actorUserId:"u1",reason:"Cancelled"}),/require payment correction or refund/);});

test("cross-order payment cannot be corrected",async()=>{const r=repo();r.ledger[0].orderId="o2";await assert.rejects(()=>correctPaymentTender(r,{orderId:"o1",paymentId:"p1",newTender:"CARD",actorUserId:"u1",reason:"Wrong",idempotencyKey:"c-x"}),/PAYMENT_NOT_FOUND/);});
test("cross-order item cannot be voided",async()=>{const r=repo();r.lockOrder=async()=>({id:"o1",operationalStatus:"OPEN",financialStatus:"UNPAID",total:0});await assert.rejects(()=>voidOrderItem(r,{orderId:"o1",orderItemId:"foreign",quantity:1,actorUserId:"u1",reason:"Wrong item"}),/ORDER_ITEM_NOT_FOUND/);});
test("item refund stores historical gross discount tax allocation",async()=>{const r=repo();const out:any=await refundOrderItems(r,{orderId:"o1",items:[{orderItemId:"i1",quantity:1}],tender:"CASH",actorUserId:"u1",reason:"Customer return",idempotencyKey:"ri-1"});assert.deepEqual(out.allocations[0],{orderItemId:"i1",quantity:1,gross:5000,discount:500,tax:675,total:5175});});
