export type Dimension="BUSINESS_DATE"|"HOUR"|"ORDER_TYPE"|"ITEM"|"CATEGORY"|"VARIANT"|"MODIFIER"|"CASHIER"|"WAITER"|"TABLE"|"TENDER"|"SHIFT"|"DISCOUNT"|"TAX_RATE"|"ORDER_STATUS";
export type Metric="QUANTITY"|"ORDER_COUNT"|"GUEST_COUNT"|"GROSS_SALES"|"DISCOUNTS"|"NET_BEFORE_TAX"|"TAX"|"NET_SALES"|"AVERAGE_ORDER"|"AVERAGE_ITEM_PRICE"|"REFUNDS"|"VOIDS"|"CASH_PAYMENTS"|"CARD_PAYMENTS"|"ONLINE_PAYMENTS";
export type FilterKey="ORDER_TYPE"|"CATEGORY"|"ITEM"|"CASHIER"|"WAITER"|"TENDER"|"SHIFT"|"STATUS"|"TABLE";
export type SortDirection="ASC"|"DESC";
export interface CustomReportDefinition {name:string;dimensions:Dimension[];metrics:Metric[];filters:Partial<Record<FilterKey,string[]>>;sort?:{field:Dimension|Metric;direction:SortDirection};compare?:"NONE"|"PREVIOUS_PERIOD"|"PREVIOUS_YEAR";limit?:number}
export interface FactRow {businessDate:string;hour:number;orderId:string;orderType:string;orderStatus:string;item:string;category:string;variant?:string;modifier?:string;cashierUserId:string;waiterUserId?:string;table?:string;shiftId?:string;tender?:string;discountName?:string;taxRateBps?:number;quantity:number;guestCount:number;gross:bigint;discount:bigint;tax:bigint;net:bigint;refund:bigint;voidAmount:bigint;payment:bigint}
export interface CustomReportRow {key:Record<string,string>;metrics:Record<string,bigint>}
export const REPORT_PRESETS:Readonly<Record<string,Pick<CustomReportDefinition,"dimensions"|"metrics">>>=Object.freeze({
 "Item-wise Sales (PMIX)":{dimensions:["CATEGORY","ITEM"],metrics:["QUANTITY","GROSS_SALES","DISCOUNTS","NET_SALES","AVERAGE_ITEM_PRICE"]},
 "Hourly Sales":{dimensions:["HOUR"],metrics:["ORDER_COUNT","GUEST_COUNT","NET_SALES","AVERAGE_ORDER"]},
 "Cashier Performance":{dimensions:["CASHIER"],metrics:["ORDER_COUNT","NET_SALES","AVERAGE_ORDER","REFUNDS","VOIDS"]},
 "Tender Analysis":{dimensions:["TENDER"],metrics:["NET_SALES","CASH_PAYMENTS","CARD_PAYMENTS","ONLINE_PAYMENTS","REFUNDS"]},
 "Modifier Performance":{dimensions:["ITEM","MODIFIER"],metrics:["QUANTITY","NET_SALES"]}
});
export function validateDefinition(d:CustomReportDefinition){if(!d.name.trim())throw new Error("REPORT_NAME_REQUIRED");if(d.dimensions.length<1||d.dimensions.length>4)throw new Error("REPORT_DIMENSIONS_INVALID");if(d.metrics.length<1||d.metrics.length>12)throw new Error("REPORT_METRICS_INVALID");if(new Set(d.dimensions).size!==d.dimensions.length)throw new Error("REPORT_DIMENSION_DUPLICATE");if(new Set(d.metrics).size!==d.metrics.length)throw new Error("REPORT_METRIC_DUPLICATE");if(d.limit!==undefined&&(d.limit<1||d.limit>10000))throw new Error("REPORT_LIMIT_INVALID")}
const dim=(f:FactRow,d:Dimension):string=>({BUSINESS_DATE:f.businessDate,HOUR:String(f.hour).padStart(2,"0"),ORDER_TYPE:f.orderType,ITEM:f.item,CATEGORY:f.category,VARIANT:f.variant??"",MODIFIER:f.modifier??"",CASHIER:f.cashierUserId,WAITER:f.waiterUserId??"",TABLE:f.table??"",TENDER:f.tender??"",SHIFT:f.shiftId??"",DISCOUNT:f.discountName??"",TAX_RATE:String(f.taxRateBps??0),ORDER_STATUS:f.orderStatus}[d]);
function filterMatch(f:FactRow,k:FilterKey,allowed:string[]):boolean{if(!allowed.length)return true;const value=({ORDER_TYPE:f.orderType,CATEGORY:f.category,ITEM:f.item,CASHIER:f.cashierUserId,WAITER:f.waiterUserId??"",TENDER:f.tender??"",SHIFT:f.shiftId??"",STATUS:f.orderStatus,TABLE:f.table??""}[k]);return allowed.includes(value)}
function addMetric(target:Record<string,bigint>,m:Metric,f:FactRow,seen:Set<string>){switch(m){case"QUANTITY":target[m]=(target[m]??0n)+BigInt(f.quantity);break;case"ORDER_COUNT":if(!seen.has(f.orderId)){target[m]=(target[m]??0n)+1n;seen.add(f.orderId)}break;case"GUEST_COUNT":if(!seen.has("g:"+f.orderId)){target[m]=(target[m]??0n)+BigInt(f.guestCount);seen.add("g:"+f.orderId)}break;case"GROSS_SALES":target[m]=(target[m]??0n)+f.gross;break;case"DISCOUNTS":target[m]=(target[m]??0n)+f.discount;break;case"NET_BEFORE_TAX":target[m]=(target[m]??0n)+(f.gross-f.discount);break;case"TAX":target[m]=(target[m]??0n)+f.tax;break;case"NET_SALES":target[m]=(target[m]??0n)+f.net;break;case"REFUNDS":target[m]=(target[m]??0n)+f.refund;break;case"VOIDS":target[m]=(target[m]??0n)+f.voidAmount;break;case"CASH_PAYMENTS":if(f.tender==="CASH")target[m]=(target[m]??0n)+f.payment;break;case"CARD_PAYMENTS":if(f.tender==="CARD")target[m]=(target[m]??0n)+f.payment;break;case"ONLINE_PAYMENTS":if(f.tender==="ONLINE")target[m]=(target[m]??0n)+f.payment;break;case"AVERAGE_ORDER":case"AVERAGE_ITEM_PRICE":break}}
export function runCustomReport(facts:FactRow[],d:CustomReportDefinition):CustomReportRow[]{validateDefinition(d);const filtered=facts.filter(f=>Object.entries(d.filters).every(([k,v])=>filterMatch(f,k as FilterKey,v??[])));const groups=new Map<string,{row:CustomReportRow;seen:Set<string>}>();for(const f of filtered){const key=Object.fromEntries(d.dimensions.map(x=>[x,dim(f,x)]));const id=JSON.stringify(key);const g=groups.get(id)??{row:{key,metrics:{}},seen:new Set<string>()};for(const m of d.metrics)addMetric(g.row.metrics,m,f,g.seen);groups.set(id,g)}for(const {row,seen} of groups.values()){if(d.metrics.includes("AVERAGE_ORDER")){const orders=[...seen].filter(x=>!x.startsWith("g:")).length||new Set(filtered.filter(f=>d.dimensions.every(x=>dim(f,x)===row.key[x])).map(f=>f.orderId)).size;const net=row.metrics.NET_SALES??filtered.filter(f=>d.dimensions.every(x=>dim(f,x)===row.key[x])).reduce((n,f)=>n+f.net,0n);row.metrics.AVERAGE_ORDER=orders?net/BigInt(orders):0n}if(d.metrics.includes("AVERAGE_ITEM_PRICE")){const qty=row.metrics.QUANTITY??filtered.filter(f=>d.dimensions.every(x=>dim(f,x)===row.key[x])).reduce((n,f)=>n+BigInt(f.quantity),0n);const net=row.metrics.NET_SALES??filtered.filter(f=>d.dimensions.every(x=>dim(f,x)===row.key[x])).reduce((n,f)=>n+f.net,0n);row.metrics.AVERAGE_ITEM_PRICE=qty?net/qty:0n}}
 let out=[...groups.values()].map(x=>x.row);if(d.sort){const s=d.sort;out.sort((a,b)=>{const av=s.field in a.metrics?a.metrics[s.field]??0n:a.key[s.field]??"";const bv=s.field in b.metrics?b.metrics[s.field]??0n:b.key[s.field]??"";const c=typeof av==="bigint"&&typeof bv==="bigint"?(av<bv?-1:av>bv?1:0):String(av).localeCompare(String(bv));return s.direction==="DESC"?-c:c})}return out.slice(0,d.limit??1000)}
export function csvExport(headers:string[],rows:(string|number|bigint)[][]):string{const q=(v:unknown)=>`"${String(v).replaceAll('"','""')}"`;return [headers.map(q).join(","),...rows.map(r=>r.map(q).join(","))].join("\r\n")}
